# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&?useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: mysqlpwd@123
  flyway:
    locations: classpath:db/
